BourbonWarfare/POTATO

addons/aceSettings/$PBOPREFIX$, addons/aceSettings/config.cpp, addons/aceSettings/script_component.hpp
#12
These just change the defaults but do not force (lock) the settings, so mission makers can still set to whatever they want.
If we want we can remove these from the description.ext in BWMF
Ref http://ace3mod.com/wiki/framework/settings-framework.html#load-order
=> Change some default ace settings

addons/setVehicleAmmo/$PBOPREFIX$, addons/setVehicleAmmo/CfgEden.hpp, addons/setVehicleAmmo/CfgEventHandlers.hpp, addons/setVehicleAmmo/XEH_postInit.sqf, addons/setVehicleAmmo/XEH_preInit.sqf, addons/setVehicleAmmo/config.cpp, addons/setVehicleAmmo/functions/fnc_attributeLoad.sqf, addons/setVehicleAmmo/functions/fnc_attributeSave.sqf, addons/setVehicleAmmo/functions/fnc_initVehicle.sqf, addons/setVehicleAmmo/functions/script_component.hpp, addons/setVehicleAmmo/script_component.hpp
Close #2
Allows changing vehicle magazine counts via 3den interface.
So not it's easy to do stuff like limit the mortar to just flares.
It can be a little cluttered because it shows all magazines the weapon is capable of firing (3 different tracer colors for each ammo type), we could limit it to just default magazines.
=> Set Vehicle Ammo in 3den

addons/briefing/CfgEden.hpp, addons/briefing/XEH_PREP.hpp, addons/briefing/XEH_postInit.sqf, addons/briefing/functions/fnc_addBriefingToUnit.sqf, addons/briefing/functions/fnc_convertNewLineToHTML.sqf
Can just hit Shift+Enter to insert new lines in the eden briefing editor
=> Briefings - Add support for 1.58 multiline input

addons/safeStart/XEH_postInit.sqf, addons/safeStart/config.cpp, addons/safeStart/gui_safeStart.hpp
Resolves #7 and will allow us to activate safestart using ACE_Settings instead of calling the old pabst function from the init.sqf
=> Safestart updates

addons/markers/XEH_postInit.sqf, addons/markers/functions/fnc_addMarkerInfoToHash.sqf, addons/markers/functions/fnc_drawMarkers.sqf
The game seems to still create all groups even if they are not slotted.
So markers is adding markers for all groups and draws icons at [0,0,0]
This just moves them out of the way.
Example, running bwmf with no AI and just me slotted:
=> Fix markers being shown for empty groups

addons/miscFixes/config.cpp
Should lighten up the SMAW enough to make it a viable replacement for BluFor MAT teams. The gunner should be able to hold 5 magazines (one loaded) with the spotter holding four spare mags.
=> SMAW playability tweaks

addons/miscFixes/CfgMagazines.hpp, addons/miscFixes/CfgVehicles.hpp, addons/miscFixes/CfgWeapons.hpp, addons/miscFixes/config.cpp
- Removes the ACRE emplaced weapon fix (it appears to be no longer valid https://github.com/IDI-Systems/acre2/blob/master/addons/sys_attenuate/fnc_getVehicleAttenuation.sqf https://github.com/IDI-Systems/acre2/blob/master/addons/sys_attenuate/CfgVehicles.hpp )
- Updates the SMAW box to have more ammo + ranging optic.
- Separates most of the configs into their own files.
=> Misc fixes to misc fixes

addons/assignGear/CfgEventHandlers.hpp, addons/assignGear/XEH_PREP.hpp, addons/assignGear/XEH_preInit.sqf, addons/assignGear/functions/fnc_addItemsToContainer.sqf, addons/assignGear/functions/fnc_assignGearMan.sqf, addons/assignGear/functions/fnc_assignGearVehicle.sqf, addons/assignGear/functions/fnc_cleanPrefix.sqf, addons/assignGear/functions/fnc_getContainerInfo.sqf, addons/assignGear/functions/fnc_getLinkedIndex.sqf, addons/assignGear/functions/fnc_getLoadoutFromConfig.sqf, addons/assignGear/functions/fnc_getWeaponArray.sqf, addons/assignGear/functions/fnc_setWeaponAttachment.sqf, addons/assignGear/script_component.hpp
hooo boy, major update to assign gear.
- Added a frame delay to the assign gear (man and vehicle) scripts to help with the `F_Gear` and JIP issues (ref #94 ).  `F_Gear` seems to work much better, JIPing remains to be seen.
- Add `handgunAttachments` to the available loadout fields (mainly for competitionist sake, since we have the launcher attachments as well)
- Break `getLoadoutFromConfig` into a few helper functions to A. reduce SQF calls (define functions once, instead of each run) and B. to hopefully helpfully break down some of the 'mega code' into more readable parcels.
- Add more debugging around assignGearMan to hopefully give better benchmarking.
- Add ability to have ambiguous loadouts. The TL;DR of this feature is to have one loadout (german, british, whatever) usable for all …
=> Assign Gear refactor/update

addons/briefing/functions/fnc_addCredits.sqf, addons/markers/XEH_postInit.sqf, addons/miscFixes/CfgEventHandlers.hpp, addons/miscFixes/XEH_serverPostInit.sqf, addons/spectate/XEH_postServerInit.sqf
Tested with a single client on dedicated (as well as JIP tests), no ill side effects noticed. Markers and spectate group created before timeout.
@PabstMirror can you take a quick sanity check?
=> Add group cleanup and setup markers and spectate to wait for cleanup

addons/markers/XEH_PREP.hpp, addons/markers/XEH_postInit.sqf, addons/markers/functions/fnc_checkForMapMarkerColor.sqf, addons/markers/functions/fnc_setMapMarkerColor.sqf, addons/markers/functions/fnc_setMarker.sqf, addons/markers/script_component.hpp
(based off of #128 )
Preset's a unit's map marking color based on the unit's group or the leader of the group's marker.
@PabstMirror I will admit it's hacky as fuck, but functional.
=> Map marker color

addons/respawn/functions/fnc_respawnClient.sqf, addons/respawn/functions/fnc_triggerRespawn.sqf, addons/spectate/XEH_postServerInit.sqf, addons/spectate/functions/fnc_init.sqf, addons/zeusFactory/functions/fnc_createGroup.sqf, addons/zeusFactory/functions/fnc_createTransport.sqf, addons/zeusHC/ACE_Settings.hpp, addons/zeusHC/functions/fnc_createCrew.sqf, addons/zeusHC/functions/fnc_createEntityDismounts.sqf, addons/zeusHC/functions/fnc_createGroup.sqf, addons/zeusHC/functions/fnc_fixGroup.sqf
In 1.68 they expanded the max groups per size to 288, so I updated our limit to 280 (incase someone spawns a lot of 1/2 man groups)
I also used the expanded syntax for explicit cleanup/persistence.
=> Expand max groups, use createGroup array syntax

addons/respawn/functions/fnc_respawnClient.sqf, addons/respawn/functions/fnc_triggerRespawn.sqf
- Add delay after group creation to add units to it (should allow time for the group variables to be properly set)
- Change how group leaders are selected, make sure it's executed where the group is local
=> Respawn fixes

addons/noRadar/config.cpp
After 1.70 changes this isn't really needed as much
Changes to a vehicle's radar will have to be done differently.
This still leaves the vehicles as available, so shouldn't break anything.
Can remove later.
=> Deprecate no radar

addons/assignGear/XEH_preInit.sqf, addons/assignGear/functions/fnc_assignGearMan.sqf, addons/assignGear/functions/fnc_assignGearVehicle.sqf
Changes:
- Use core funcs when pulling information from the configs
- Move the XEHs from init to initPost (should have the frame delay built in now)
- Make gear apply to units on 3DEN load
- Make sure allowChangeableOptics is defined even if potato is off
- Add backpack validation to the gear watchdog
- Change the vehicle gear class lookup to scan through available faction/loadout combos before looking at the default loadout.
Questions:
Do we want to look at ALL factions under a side, instead of the limited scope (add some caching once found)? Would increase initial lookup time, but would not need to update this code if we expand our set of default factions?
=> Assign gear tweaks

addons/missionTest/functions/fnc_onMissionSave.sqf
Use CFUNCs for config lookups
Changes how RHS disposables are checked, can duplicate for BAF if they ever update to autoload their launchers.
=> Use config values instead of string type compare

addons/assignGear/functions/fnc_addItemsToContainer.sqf, addons/assignGear/functions/fnc_getWeaponArray.sqf
Cleans up a couple of non-problem warnings, mainly from us using empty strings in macros.
`#define RIFLE_ATTACHMENTS ""`
```
[POTATO-assignGear] - Attachment [] not compatible with [rhs_weap_mk18_wd]
```
`#define AT_MAG ""` // Because: ("" splitString ":") = []
```
[POTATO-assignGear] Item Not Found [any:scalar NaN]
[POTATO] (assignGear) ERROR:  z\potato\addons\assignGear\functions\fnc_addItemsToContainer.sqf:72
[any:scalar NaN] Bad Item Classname
```
`#define FAC_MAGAZINES "Laserbatteries"` // Because getWeaponArray takes out a magazine, so it becomes "Laserbatteries:0"
```
[POTATO] (assignGear) WARNING: ~~~~~~~~~ Items not added for: Soldier_unarmed_F ~~~~~~~~~~~ z\potato\addons\assignGear\functions\fnc_getLoadoutFromConfig.sqf:86
[POTATO] (assignGear) WARNING: Items: [] …
```
=> Assign Gear - Handle empty string warnings

addons/adminMenu/XEH_postInit.sqf, addons/assignGear/XEH_PREP.hpp, addons/assignGear/XEH_clientPostInit.sqf, addons/assignGear/XEH_preInit.sqf, addons/assignGear/functions/fnc_assignGearMan.sqf, addons/assignGear/functions/fnc_requestPlayerGear.sqf
Resolves #94 
This PR will:
- Move assignGearMan to initPost
- Add actual JIP handling (tested on local dedicated, should be interesting in large scale dedicated)
- Move google handling to assignGearMan
- Refactor the reset gear menu tool to use the new function
- Ensure assign gear is only run on the server to better leverage caching
If this works reliably in session, we should be able to remove the watch dog (might need to keep it for AI?)
Potential downsides: 
- If the server initPost actually works on JIPs (which is historically has not) assign gear could run twice per JIP (with no benefit)
- Moving the googles stuff to assign gear might lead to strange stuff for AI?
=> Reflow assign gear for JIPs

addons/assignGear/XEH_PREP.hpp, addons/assignGear/XEH_clientPostInit.sqf, addons/assignGear/XEH_preInit.sqf, addons/assignGear/functions/fnc_addItemsToContainer.sqf, addons/assignGear/functions/fnc_assignGearMan.sqf, addons/assignGear/functions/fnc_cleanPrefix.sqf, addons/assignGear/functions/fnc_getLoadoutFromConfig.sqf, addons/assignGear/functions/fnc_getWeaponArray.sqf, addons/assignGear/functions/fnc_isOpticMagnified.sqf, addons/assignGear/functions/fnc_setWeaponAttachment.sqf, addons/assignGear/script_component.hpp
Some pretty minor cleanup for assign gear:
- Simplifies the goggle handling by just setting it in the setUnitLoadout array, instead of handling it separately.
- Adds a function to check if an optic is considered magnified, added a cache lookup on the optic class name. Should help a bit with maintenance and a bit on the optic lookup, only 'problem' is the client (optix) vs server (assignGear) locality nmot fully leveraging the caching.
- Moves a lot of the BI based defined to the scripting component file for easier lookup/tweaking.
- Some minor style tweaks
=> Some cleanup for assign gear

addons/adminMenu/functions/fnc_uihook_teleportButton.sqf
This should:
- Check for empty vehicle positions before trying to teleport
- Not kill a player when teleporting them from the water to land
- Allow teleportation to raised surfaces (like aircraft carriers and houses)
- Minor logic flow and message cleanup.
=> Fix some teleport issues

addons/respawn/Displays.hpp
Text was center aligned, so different resolutions have vastly different results, should be fixed now.
=> Fix client respawn text

addons/assignGear/XEH_clientPostInit.sqf
It looks like when people JIP during the load in period, their client gear runs before they actually get a body. This should delay it until the game is past the map screen.
=> Add delay to jip at mapscreen

addons/massCompat/CfgWeapons.hpp, addons/massCompat/config.cpp, addons/miscFixes/CfgWeapons.hpp, addons/miscFixes/config.cpp
This PR will:
- Add cross magazine support between CUP and HLC (M)G36es.
- Add display support for loading CUP 30/100rnd mags into HLC (M)G36es
- Allow the iron sighted HLC G36es to be zeroed from 100-500m
These changes should allow the HLC/CUP (M)G36es to be better integrated into sessions
=> Add HLC<->CUP G36 support

addons/aceSettings/XEH_preInit.sqf
Adds a setting that turns off RHS engine startup delay scripting. Discussion point: should we leave this defaulted to true, then update it in BWMF?
Also cleans up STUI variables that are unused.
=> Add engine script setting

addons/core/CfgAmmo.hpp
Title.
Use case: Mission with protesting AI and you want players to get freaked out. Default "Stone" class not suitable as for it is not a stone model and it explodes, kinda negating the point.
=> Make AI throw potatos when met with threat

addons/aiCfgFixes/CfgAmmo.hpp, addons/aiCfgFixes/CfgMagazines.hpp, addons/aiCfgFixes/config.cpp, addons/aiCfgFixes/functions/fnc_ensurePlayerBurst.sqf, addons/aiCfgFixes/functions/fnc_generateAmmo.sqf, addons/aiCfgFixes/functions/fnc_generateWeapons.sqf
Currently AI will not fire MI-8 or MI-24 rocket pods at players if they are not in a vehicle. This changes that, and makes it so the AI will consider shooting regular RPG rockets at players as well
Why:
Currently when a MI-8 with rocket pods fly overhead players ignore it because they dont shoot their rockets. Make that assumption go away with this, and make COOPs more deadly
Custom ammo type implemented as to not break anything that uses R_80mm_HE
=> Make AI shoot rockets more often

addons/cswCompat/CfgWeapons.hpp, addons/cswCompat/script_component.hpp
change from csw to apl data. Fixes click through error and adds model back to CUP weapons
=> Update backpacks to reflect latest CSW change

addons/aiCfgFixes/CfgVehicles.hpp, addons/aiCfgFixes/config.cpp
AI currently don't shoot at you at far ranges because they dont have vision. This change makes them see at further ranges, and keep seeing at that range
If an AI group sees you at 500m+ they will keep firing at you for quite a distance until you out-range their weapons or you break line of sight. They will then keep observing that area so if you pop out again, they will light you up. Cool emergent behaviours come out of this, such as an actual AI Base of Fire at distance preventing a player push onto them
In testing the AI can theoretically see out to 700m and engage targets. Because of previous AI fixes they are limited to their weapon configuration and therefore the AR's will engage with long bursts with rifle fire coming at few second intervals. They are incredibly inaccurate at this …
=> Make AI see farther away

addons/aiVehicleBail/CfgVehicles.hpp, addons/aiVehicleBail/XEH_PREP.hpp, addons/aiVehicleBail/config.cpp, addons/aiVehicleBail/functions/fnc_addEventHandler.sqf, addons/aiVehicleBail/functions/fnc_detonate.sqf, addons/aiVehicleBail/functions/fnc_handleBail.sqf, addons/aiVehicleBail/functions/fnc_handleCookoff.sqf, addons/aiVehicleBail/functions/fnc_handleVehicleDamage.sqf, addons/aiVehicleBail/initSettings.sqf, addons/aiVehicleBail/script_component.hpp, addons/aiVehicleBail/script_macros.hpp
Adds cookoff to vehicles when they receive damage to certain spots. Because this doesn't modify the damage vehicles will not be forced to cook off in order to die.
Features:
-Cook-off fire that destroys the vehicle after 15 seconds (occupants can bail out)
-Cook-off detonations that leaves the vehicle "alive" (occupants dies instantly)
-Both things can happen during the same cook-off sequence
The system works by rolling a dice every time certain spots are damaged, and if the check is high enough the vehicle will cook off. The dice roll is influenced by the ammo that hit it (sort of), how much ammo and how much fuel is in the vehicle depending on where it gets hit. Unfortunately this means that each vehicle has to be configured for this, but it won't break anything if it isn't.
Why do we …
=> Add Vehicle Cookoff that doesn't override destroyed state

addons/aiVehicleBail/functions/fnc_handleCookoff.sqf
Tweak value such that you probably wont cookoff a vehicle with bullets
=> Make non-warhead ammunition less effective against vehicles

addons/aiVehicleBail/CfgVehicles.hpp
Compatibility for CUP vehicles while `ace_vehicleDamage` is being tested -- will be overridden by #247 when that is merged
=> ACE VehicleDamage compats -- Testing Period

addons/miscMedical/XEH_postInit.sqf, addons/settings/BW_Settings.sqf
Changes BW_Settings.sqf to use cardiac arrest with the settings tested in December's long coop.
=> Cardiac Arrest Implementation

addons/miscFixes/CfgVehicles.hpp
Duplicates the Carryall backpack in the style of a Battle Belt. Mainly to be used for heavy weapons teams to get rid of the weapon/mount clipping.
=> Battle Belt XL

addons/aiCfgFixes/config.cpp, addons/aiVehicleBail/config.cpp, addons/core/script_macros.hpp, addons/core/script_macros_debug.hpp, addons/cswCompat/config.cpp, addons/cswCompat/script_component.hpp, addons/filledSmoke/config.cpp, addons/flares/config.cpp, addons/hitEffects/config.cpp, addons/massCompat/config.cpp, addons/miscFixes/config.cpp, addons/miscMedical/XEH_postInit.sqf, addons/radios/config.cpp, addons/spectate/XEH_postClientInit.sqf, addons/spectate/config.cpp, addons/spectate/functions/fnc_setup.sqf, addons/units/CfgVehicles.hpp, addons/zeusFactory/functions/fnc_addVehiclesToArray.sqf, addons/zeusHC/CfgEventHandlers.hpp, addons/zeusHC/CfgVehicles.hpp, addons/zeusHC/XEH_PREP.hpp, addons/zeusHC/XEH_postInit.sqf, addons/zeusHC/XEH_postServerInit.sqf, addons/zeusHC/functions/fnc_autoModule_createLocal.sqf, addons/zeusHC/functions/fnc_autoModule_module.sqf, addons/zeusHC/functions/fnc_autoModule_setup.sqf, addons/zeusHC/functions/fnc_createCrew.sqf, addons/zeusHC/functions/fnc_getSpawnMachineId.sqf
Adds zeusHC modules for mission vehicles at runtime.
Vehicles also show up in factory
Guide for Mission makers:
- Place vic with the camo you want
- Place a unit of the side you want near the vic
it uses the side of the crew or nearest unit to the vic to determine what side it is
once all zeuses have loaded in you can then delete them or do whatever
Vehicles should show up in HC spawn modules and in factory
=> Create zeusHC modules from pre-placed vehicles

addons/missionTesting/functions/fnc_displayMenu.sqf
Adds a forum link on the mission testing menu. Nothing special at the moment, but will open the Finished Missions subforum in the users default browser.
=> Add forum button to Testing Menu

addons/missionTest/functions/fnc_onMissionSave.sqf, addons/missionTesting/CfgEden.hpp, addons/missionTesting/config.cpp, addons/missionTesting/functions/fnc_displayMenu.sqf, addons/safeStart/XEH_PREP.hpp, addons/safeStart/XEH_preInit.sqf, addons/safeStart/functions/fnc_missionTimeWarning.sqf, addons/safeStart/script_component.hpp
Adds a mission attribute to the "Mission Testing Attributes" for SS length and Mission Length.
Provides a warning to admins and Curators at 15mins before the end of the mission length, and one at the expiry of mission time. 
Creates a marker with the listed mission end time. 
Includes a fix for the forum link in the Mission Testers checklist. 
Known issues:
Will create two warnings if for whatever reason safestart is re-added and removed. Will not effect the time that the message is displayed. 
If in the case above, this does not update the marker. Have tried to get this working but for whatever reason it will not at this time. Might need some help. 
EDIT: https://github.com/BourbonWarfare/POTATO/pull/295/commits/9e1caa0f287c5b9b1b7fd2d663a38a66e945e722 With this commit I have added a …
=> SafeStart additions

addons/zeusFactory/UI_RscAttributes.hpp, addons/zeusFactory/functions/fnc_ai_attack.sqf, addons/zeusFactory/functions/fnc_ai_garrison.sqf, addons/zeusFactory/functions/fnc_ai_paradrop.sqf, addons/zeusFactory/functions/fnc_ai_patrol.sqf, addons/zeusFactory/functions/fnc_ai_search.sqf, addons/zeusFactory/functions/fnc_createTransport.sqf, addons/zeusFactory/functions/fnc_dispatch.sqf, addons/zeusFactory/functions/fnc_getTransportType.sqf, addons/zeusFactory/functions/fnc_zeusAttributes_place.sqf
* Change Paradrop script to be better; implements my paradrop script. No more helicopters hanging in the air awkwardly
* AI will now always occupy vehicle gunner seats while before they only spawned in IFVs. This should allow AI helicopters to have door gunners and AI cars to have gunners so they can defend themselves
* AI will now have option to use LAMBS waypoints to complete their mission
* Add check-box to allow Zeus to tell AI to execute order at target mark after dismount, or dismount location
* Add check-box to allow Zeus to tell AI to use LAMBS AI waypoints after dismount
These should be good changes that allow for better flow in missions. Nothing tested in multiplayer/dedicated server, I don't see why anything wouldn't work however. This should make AI a bit more realistic to …
=> AI Factory Updates

addons/settings/BW_Settings.sqf
this being `0` means that we don't get the fire spitting out the tops of vehicles, ammo boxes dont explode with the ammo inside, vehicle ammo doesn't explode
=> re-enable cookoff

addons/missionTesting/functions/fnc_displayMenu.sqf
Want this to be the player unit and not the RC unit named in the case of mission testing using the "Play As Character" or using Zeus to RC a unit. This will cause the wrong menu to open.
=> Remove ACE_PLAYER

addons/adminComs/XEH_postInit.sqf, addons/missionTest/functions/fnc_onMissionSave.sqf, addons/missionTesting/CfgEden.hpp, addons/missionTesting/XEH_postInit.sqf, addons/missionTesting/functions/fnc_displayMenu.sqf, addons/missionTesting/functions/fnc_generateReport.sqf, addons/safeStart/XEH_postInit.sqf, addons/safeStart/functions/fnc_missionTimeWarning.sqf, addons/safeStart/script_component.hpp
Have added the ability to open the mission making checklist in 3Den. Available through [POTATO --> Open Testing Menu]
- Time Keeper has been changed so that we no longer get weird values in the Attributes Menu. The defaults have been set to 0 in the attributes menu.
- This means that they will also report in missionTest module if a value has been set. 
- The time keeper now creates local markers so that they it can be moved around the map to make it easier to reference. 
- I am a little concerned about the method used here. I don't believe that it will create a boat load of new markers for all players in the same spot, but it needs testing.
- Briefing is not longer Brieifing (Thanks kilo).
- Mission timers are also now in the MM report and will show in the testing menu for quicker …
=> Mission testing in 3Den & Time Keeper changes

addons/miscFixes/CfgVehicles.hpp
Make vanilla "Chinook" (aka Huron) and EH302 (IDAP/FIA heavy transport heli) float on water. 
This now matches CUP Chinook/CH-53e heavy lift helos. 
This change should eventually be extended to all helicopters from mods that could feasibly "float" (aka hover on surface of water for pseudo-helocast extract). I just don't currently have time to go through the editor and find all helos that should do this. I'll try to outsource it.
=> Normalize water floatation for vanilla heavy-lift helicopters to match CUP 

addons/filledSmoke/config.cpp
Noted during testing of a mission on Isla Pera that even on land smoke was not filling as expected. 
This appeared to be a result of being near but not in water. 
These adjusted values change how the smoke behaves on the fringes of water. Any smoke created will plume above the water. And any smoke that is created underwater will not plume and fill, unless it is very very close to the surface. 
Example images from Isla Pera Before:
After:
After also tested in Tanoa:
=> Adjust Smoke Plume near or on the fringes of water

addons/assignGear/XEH_PREP.hpp, addons/assignGear/XEH_preInit.sqf, addons/assignGear/functions/fnc_assignGearPotatoBox.sqf, addons/assignGear/functions/fnc_assignGearSupplyBox.sqf
Blame chesh for me making this
Allows users to quickly set supply box loadouts in the same way you can for vehicles
=> Allow BWMF to set any supply-crate ammo like loadout files

addons/miscFixes/patchPLA/config.cpp
This patch is intended to normalize the PLA Armored Vehicles mod's armor to vanilla standards so as to fix the ongoing issue where infantry AT and equivalent vehicles cannot do meaningful damage to the PLA vehicles.
Specifically, this patch affects the following vehicles:
- ZBL09
- ZTL11
- ZBD04A
- ZBD05
- ZTD05
=> PLA Armor Normalization

addons/miscFixes/CfgVehicles.hpp
Adds a CBRN backpack but with an expanded inventory size. Still requires the Contact DLC to use.
=> CBRN Backpack but Bigger

addons/miscFixes/CfgVehicles.hpp
Increase storage capacity of Contact DLC Radio Backpack to hold ACRE radios and radio accessories. Should hold (1) large radio, (2) medium radios, and (1) ground-spike antenna/mast assembly.
=> Increase Contact DLC Radio Bag storage capacity

addons/miscFixes/patchPTV/config.cpp
Adds compat between CUP GL ammunition and PTV GL weapons
Alters all PTV vests to be have armor values in line with CUP armor values; previously, vests had max armor and would prevent any penetration unless from .50cal+
=> PTV CUP Compat + Armor Normalization

addons/miscFixes/patchPTV/config.cpp
- Adds JSRS sound compat, fixing the overly loud sound but replaces the unique sound with generic JSRS sound.
- PTV's last update changed the class structure for the weapons. This fixes the errors caused by that - specifically, the sights for the GL rifles being unusable as a result of this patch.
=> JSRS Compat + Class Structure fix

addons/miscFixes/CfgVehicles.hpp, addons/miscFixes/patchPTV/config.cpp
Fixes
```
[CBA] (xeh) WARNING: ptv_Pnd_Base_F does not support Extended Event Handlers! Addon: 3092130870
[CBA] (xeh) WARNING: ptv_Warrior_Base_F does not support Extended Event Handlers! Addon: 3092130870
```
=> PatchPTV - Fix XEH configs

addons/zeusHC/CfgVehicles.hpp
Diversifies the rifleman units in modules that spawn more than one rifleman. Specifically, this affects the Patrol (2), Squad (8), and Dismount (6) modules.
This enables mission makers to use loadouts that have defined rifleman_02 and rifleman_03 kits, but does not affect the use of legacy loadouts that do not have rifleman_02 and rifleman_03 defined as those classes inherit from rifleman by default.
An example of this coming in handy is if a mission maker wishes to represent a guerilla faction that uses a wealth of weapons that do not share a common magwell. This will allow for the MM to use an M16A2 for the base rifleman kit, an FAL for rifleman_02, and an AKM for rifleman_03 and have them be represented in the spawn groups. This is currently not possible due to the groups spawning the …
=> POTATO Spawn Module Unit Diversification

addons/bodyCleanup/$PBOPREFIX$, addons/bodyCleanup/CfgEventhandlers.hpp, addons/bodyCleanup/XEH_PREP.hpp, addons/bodyCleanup/XEH_preInit.sqf, addons/bodyCleanup/XEH_preStart.sqf, addons/bodyCleanup/XEH_serverPostInit.sqf, addons/bodyCleanup/config.cpp, addons/bodyCleanup/functions/fnc_cleanCell.sqf, addons/bodyCleanup/functions/fnc_cleanupPFH.sqf, addons/bodyCleanup/functions/fnc_debugPFH.sqf, addons/bodyCleanup/functions/fnc_getPlayerViewCones.sqf, addons/bodyCleanup/functions/fnc_initCell.sqf, addons/bodyCleanup/functions/fnc_onKill.sqf, addons/bodyCleanup/functions/fnc_uncleanCell.sqf, addons/bodyCleanup/functions/fnc_updateCellPFH.sqf, addons/bodyCleanup/functions/script_component.hpp, addons/bodyCleanup/initSettings.sqf, addons/bodyCleanup/script_component.hpp, tools/setup.py
When enabled, any `Man` type unit will be put into a bucket within a uniform grid. Periodically there will be a check against each grid cell for each human player, and if a grid cell is not visible to any player it will be marked for deletion. When marked, there is a two minute countdown before the body is removed.
Bodies can be removed in two ways depending on settings: First, basic deletion. Just deleted, gone. However, a setting can be enabled to have bodies stop being rendered and their simulation disabled. With this setting, players would be able to return to their past massacres and view the bodies without immersion being lost.
This is an experimental feature disabled by default. My plan is to coordinate with some mission makers to have this be run during their coop and for me to …
=> Add body garbage collection

addons/miscFixes/patchMELB/config.cpp
Adds forced geo-lock on zoom levels 3 and above. This assists in tracking a target when the pilot is engaged in evasive maneuvers or otherwise has to fly erratically.
Known problem: Arma geo-locking on helicopters locks on to the 0 elev point BENEATH the terrain for some reason. This happens in the vanilla vehicles and TGPs as well, so it's a platform problem :(
=> MELB QOL Fix

addons/missionTesting/functions/fnc_displayMenu.sqf
This change should allow for mission testers to also be able to see the mission summary - this is to streamline the flow of work for testers in the case that the summary is neither posted on the forums and if they forgot the summary from the slotting screen.
=> Adds Summary for Tester

addons/miscFixes/patchCUP/config.cpp, addons/miscFixes/patchCUPPTV/config.cpp
Updates a few CUP weapons to have newer/better animations. Specifically, the ACR has been changed to use the PTV HK433 animation while the old M4A1s have been updated to use the same animation as the "new" CUP M4A1s.
Weapons updated:
- ACR (5.56)
- ACR-C (5.56)
- ACR (6.8 SPC)
- ACR-C (6.8 SPC)
- M4A1 (11.3 MOE + RAS)
- M4A1 (14.5 MOE + RAS)
=> CUP Weapons Reanim

addons/miscFixes/patchRHSAFRF/config.cpp
Adds a large version of the RHS Medic Bag that is sized to fit our medic's standard amount of supplies.
=> RHS Medic Bag (Large)

.hemtt/project.toml, addons/missionModules/CfgVehicles.hpp
Adds GM's German voice to the "Set AI Identity (Voices)" mission module. Let me know if that should be in a optional compat as part of the missionModules addon instead.
=> Add GM's German voice set to "Set AI Identity (Voices)" module

addons/miscFixes/patchPLA/config.cpp
PLA updated their config syntax/class names recently which broke this patch and caused a Crash-to-Lobby when the ZTL-11 and ZTD-05 were present in a mission.
This *should* resolve that issue.
=> Fixes Crash-To-Lobby bug caused by PLA

addons/miscFixes/patchCUP/config.cpp
Tunes the CUP UK Vz.59 LMG recoil down a notch in order to make it more palatable when firing from a standing unsupported position.
Original values for comparison:
muzzleOuter[] = {0.71, 1.22, 0.77, 0.32};
kickBack[] = {0.026, 0.064};
temporary = 0.005;
permanent = 0.2;
=> CUP UK Vz.59 Recoil Tuning

addons/miscFixes/patchRHSAFRF/config.cpp
Brings the RHS vest armor values to be more in line with Vanilla/CUP as well as to clarify the armor level rating system which is labelled after the Russian GOST system, not NIJ like the vanilla/CUP armor systems.
This affects the following RHS AFRF vests and their subvariants:
- 6B2
- 6B3
- 6B5
- 6B13
- 6B23
=> RHS Body Armor Normalization

addons/missileGuidanceCompat/patchGM/config.cpp
I had miss-aligned these both when I first committed them, noticed during testing for #546. Probably needs a quick ACE PR as well since the MILAN is part of that now.
=> Change initial pitch on MILAN and Fagot

addons/assignGear/XEH_PREP.hpp, addons/assignGear/XEH_clientPostInit.sqf, addons/assignGear/XEH_preInit.sqf, addons/assignGear/functions/fnc_addSupplyBoxActions.sqf, addons/assignGear/functions/fnc_assignGearSupplyBox.sqf, addons/assignGear/functions/fnc_setBoxContentsFromConfig.sqf
This adds an idea kilo had/stole in the [resupply boxes suggestion on BW's discord](https://discord.com/channels/204621032428929025/1281258900728975382/1281672958061838498). It allows a mission maker to use the `CfgLoadouts` `SupplyBoxes` class to make larger boxes with multiple smaller resupply boxes inside them. See this example
```cpp
class CfgLoadouts {
// other code before or after
// Do Supply Box Loadouts
// (1 will run normaly, 0 will leave them to vanilla defaults, -1 will clear and leave empty)
setSupplyBoxLoadouts = 1;
class SupplyBoxes {
class ACE_medicalSupplyCrate {
boxCustomName = "Wild Medical Box";
TransportItems[] = {
"ACE_elasticBandage:40",
"ACE_packingBandage:20",
"ACE_epinephrine:15",
"ACE_morphine:15",
"ACE_adenosine:15",
"ACE_tourniquet:10",
"ACE_splint:10", …
```
=> Add ability to create larger supply boxes with smaller resupply boxes inside them

addons/cswCompat/patchGM/ACE_CSW_Groups.hpp, addons/cswCompat/patchGM/CfgMagazines.hpp, addons/cswCompat/patchGM/CfgVehicles.hpp, addons/cswCompat/patchGM/CfgWeapons.hpp, addons/cswCompat/patchGM/config.cpp
This PR adds CSW version of GM static weapons including:
- MG3 AA tripod
- MILAN
- Fagot
To add the MILAN and Fagot, there is some abuse of the system by treating them as "tripods." The MG3 uses current ACE master functionality to allow primary weapons to be mounted. Video on discord.
=> Add CSW for GM MG3 tripod, Fagot, and MILAN.

addons/assignGear/functions/fnc_assignGearSupplyBox.sqf, addons/assignGear/functions/fnc_assignGearVehicle.sqf, addons/assignGear/functions/fnc_assignGearVehicle_asBoxes.sqf
Current problem:
With `setSupplyBoxLoadouts = -1`, the boxes are cleared after they're set in `fnc_assignGearVehicle_asBoxes`. I had handled this for other settings using [a variable on the box](https://github.com/BourbonWarfare/POTATO/blob/8625ee16b4f5cd897fe433ef2f653146e1903fba/addons/assignGear/functions/fnc_assignGearSupplyBox.sqf#L27), but this slipped through when I was testing #539.
Fix is simple though.
=> assignGear bug fixes

addons/armor_modifier_ace/functions/fnc_handleDamage.sqf, addons/armor_modifier_ace/initSettings.inc.sqf
We didn't dive super deep into how johnB was modifying the ACE damageHanlde funciton and that's on me for not double checking his work there.
He was modifying the variable `_realDamage`, which should be the damage calculated based on the bullet's speed/ `typicalSpeed` / `hit`. Changing this makes other medical functions it may be passed to treat it as if, more damaging projectiles were what hit the unit. `_newDamage` should be related to `_realDamage` by a factor of whatever armor is relevant in the ACE/AMA "handleDamage" EH function, which it isn't quite in the current version. 
If someone would like to do a simple test to double check I'd appreciate that.
=> Fix AMA's Handling of Armor

addons/miscFixes/XEH_preInit.sqf
Fixed an error would be thrown if `ace_player` was not defined and the weapon lower shortcut was pressed.
Checking for `!alive` will handle both dead and `nullObject` settings for `ace_player`.
=> Fixed error with Weapon Lowering Shortcut

addons/armor_modifier_ace/functions/fnc_handleDamage.sqf
Updated `potato_armor_modifier_ace_fnc_handleDamage` to match changes made in current [`ace_medical_engine_fnc_handleDamage`.](https://github.com/acemod/ACE3/blob/631db9d6037ebe22219cdef3f2bad10b6f95507d/addons/medical_engine/functions/fnc_handleDamage.sqf)
=> Update AMA Handle Damage to match changes in ACE Handle Damage

addons/spectate/functions/fnc_getName.sqf
This is a simple attempt to fix missing names on the JIP/respawned units in the spectate menu. It waits for an attempt at name update to take effect, under the assumption that eventually the name is properly synced.
=> Spectate - Fix Missing Name on JIPs

addons/settings/BW_Settings.inc.sqf
ace changed the default to 0.1 from what it had been  https://github.com/acemod/ACE3/pull/10361/files
so we no longer need this, but only merge if we are going to update our ace copy
=> Settings - Revert change to terraingradientfactor

addons/miscFixes/patchHMD/config.cpp
Kimi's HMD mod broke the inheritance for the "gatling_20mm" cannon, breaking it on any dynamic pylon vehicle.
I also updated the cursorAim, ballisticsComputer, and magazines to be in-line with other, similar weapons, and to include ACE ammunition.
I haven't taken a look at the Fixed Wing PBO to see if the same thing is happening, but this at least fixed it on the vehicles that I mentioned in https://github.com/BourbonWarfare/POTATO/issues/593#issue-2634620810. This specifically includes the Tucano as being able to use the 20mm cannons now.
=> Kimi's HMD 20mm Cannon Fix

addons/filledSmoke/compatGM/CfgAmmo.hpp, addons/filledSmoke/compatGM/CfgCloudlets.hpp, addons/filledSmoke/compatGM/config.cpp, addons/filledSmoke/compatGM/script_component.hpp, addons/filledSmoke/config.cpp
Smoke grenades previously had their particles only drop on the ground, I was able to trouble shoot this to being related to having a `circleRadius` defined.
=> filledSmoke - Fix Smoke not leaving the ground and add GM compat

addons/customGear/config.cpp
This PR fixes a misnamed `config.cpp` and cleans up unnecessary includes, addressing https://github.com/BourbonWarfare/POTATO/issues/609.
=> Fix missing fauxMG5

addons/arsenalExport/functions/fnc_export.sqf
https://github.com/BourbonWarfare/POTATO/issues/608
- Brings the SNIPER_ATTACHMENTS, SPOTTER_ATTACHMENTS, and PISTOL_ATTACHMENTS exported text back in-line with what is present on BWMF loadout files
=> Export Define Text Fix

addons/customGear/README.md, addons/customGear/vestBackpacks/config.cpp
- Fixes some smersh vestBackpacks having incorrectly colored ui pictures
- Adds CWRIII ALICE LBE
- Adds M23 chest rigs in TKE and OD Green
- Adds 6Sh92 chest rigs
- Adds Raven vest
=> More vestBackpacks

addons/aiVehicleBail/XEH_postInit.sqf, addons/aiVehicleBail/functions/fnc_handleVehicleDamage.sqf, addons/assignGear/XEH_preInit.sqf, addons/assignGear/functions/fnc_assignGearMan.sqf, addons/assignGear/functions/fnc_cleanPrefix.sqf, addons/assignGear/functions/fnc_isOpticMagnified.sqf, addons/respawn/functions/fnc_addGroup.sqf, addons/respawn/functions/fnc_readConfigToVariables.sqf, addons/respawn/functions/fnc_triggerRespawn.sqf, addons/respawn/functions/fnc_ui_handleAdminLoad.sqf, addons/respawn/functions/fnc_ui_handleFactionChange.sqf, addons/respawn/functions/fnc_ui_handleGroupChange.sqf, addons/spectate/XEH_postClientInit.sqf, addons/spectate/functions/fnc_getBoundingBox.sqf, addons/spectate/functions/fnc_getGroupIcon.sqf
This replaces all CBA namespaces with hash maps. This doesn't clear up much overhead, but should create fewer objects & locations. There could be a issues with case sensitive keys, but during testing I did not run into any issues.
=> Replace CBA Namespaces with Hash Maps

addons/miscFixes/patchCUP/config.cpp
https://github.com/BourbonWarfare/POTATO/issues/592
- Increased initial acceleration to make vehicle feel more responsive
- Increased braking torque to make braking feel more responsive
- Decreased fording depth due to being able to operate despite the engine and exhaust being submurged by +1m of water over the hull
- Swapped the gunner's HMG turret from the M2 to the M3M per the wikipedia page
- Moved the countermeasures smoke from the commander's turret to the gunner's turret
=> GTK Boxer Handling + Turret Tweaks

addons/miscFixes/patchCWR/config.cpp, addons/miscFixes/patchSOG/config.cpp
This PR:
- Reverts all the base terrains back to their original cutscene
- Removes the CWR3 intro from the pool of Malden cutscenes
=> miscFixes - Revert SOG and CWR3 Main Menu Cutscene Changes

addons/zeusUtils/script_component.hpp
I used quotes instead of the QUOTE macro with a variable inside the quotes in a macro.
=> Zeus Utils - FIx define not being properly analyzed

.vscode/settings.json, addons/miscFixes/patchCUP/config.cpp
This PR fixes gunners audio being attenuated on
- HMMWVs
- Normal HMMWVs
- SOV HMMWVs
- FRAG7 HMMWVs
- Tigr - All armed variants
=> Misc Fixed - Fix CUP Gunner ACRE Attenuation

addons/adminComs/functions/fnc_mouseCatch.sqf, addons/adminMenu/functions/fnc_uihook_teleportButton.sqf, addons/core/XEH_PREP.hpp, addons/core/XEH_postInit.sqf, addons/core/functions/fnc_playerJipHint.sqf
Adds hint for player's last group when the jip in to make it faster and easier to get them back to where they should be
Remove time from admin log and moves it to tooltip
=> Core - Add last group hint when player re-jips in

addons/zeusUtils/initSettings.inc.sqf
This PR transfers the setting to enable Zeus FPS counter to "Potato - Mission Maker"
=> Create Potato - Mission Maker - Zeus Utilities section

addons/adminMenu/Interrupt_adminMenu.hpp, addons/respawn/CfgFactionClasses.hpp, addons/respawn/CfgVehicles.hpp, addons/respawn/Displays.hpp, addons/spectate/Displays.hpp
Per the response in the internal suggestions thread, this PR:
- Changes the spectator "Open Respawn" button to a "Reinforcement Slots" button
- Changes all of the `Wave Respawn Tool` text from "Respawn" to "Reinforcement"
- Change admin menu button
- Change Zeus Module names and category to transfer terminology from "Respawn" to "Reinforcement"
=> Respawn - Change text from "Respawn" to "Reinforcement" in user facing locations

addons/miscFixes/patchW35/config.cpp
W35 introduces a few changes to `B_Soldier_base_f`, some of which propagate to all (including BW) west units. The important one is the `accuracy` decrease making it harder for AI to spot players, but the other two are just things I would like reverted as well.
=> Misc Fixes - W35

addons/strongerFlashlights/CfgWeapons.hpp, addons/strongerFlashlights/config.cpp, addons/strongerFlashlights/script_component.hpp
This PR adds 4 flashlights of varying brightness and color.
- A red, yellow, and white flashlight that aren't blindingly bright but provide a multimode flashlight brighter than vanilla.
- A bright white flashlight that sits somewhere between Chesh's super bright and the other three.
Video in relevant discord channel
=> strongerFlashlights - Add 3x barely stronger flashlights and an intermediately brighter white flashlight

addons/zeusUtils/CfgUI.hpp, addons/zeusUtils/XEH_PREP.hpp, addons/zeusUtils/XEH_postInit.sqf, addons/zeusUtils/XEH_preInit.sqf, addons/zeusUtils/functions/fnc_addDraw3DEH.sqf, addons/zeusUtils/functions/fnc_changeFPSDisplayState.sqf, addons/zeusUtils/functions/fnc_changeMarkerDisplayState.sqf, addons/zeusUtils/functions/fnc_drawFPS.sqf, addons/zeusUtils/functions/fnc_drawMarkers.sqf, addons/zeusUtils/functions/fnc_removeDraw3DEH.sqf, addons/zeusUtils/initSettings.inc.sqf, addons/zeusUtils/script_component.hpp
This PR adds the ability to draw markers above the marker's holder. 
- It does not show markers for dead units or for markers detached for units
- The marker size is scale with distance and to marker map size
- Custom local settings for:
- Max marker draw distance
- Marker size
- Displaying marker text
- Created common Draw3D EH
- Updated button UI to be more readable
=> zeusUtils - Add Draw Markers Button

addons/strongerFlashlights/CfgWeapons.hpp
This PR fixes errors in the implementation of the additional flashlights in the last potato update, specifically,
- Fixes text for low brightness white flood
- Fixes reverse cycle for low brightness red
**TODO**
=> strongerFLashlights - Fix Errors

addons/zeusUtils/functions/fnc_drawMarkers.sqf
This PR properly converts from ASL to AGL for the `drawIcon3D` locations for the zeus utils drawing function
=> zeusUtils - Fix draw markers draw location

addons/vehicleCoasting/functions/fnc_vehicleCookOffHandle.sqf
This PR fixes issues with vehicle coasting:
- Bad logic allowing the system to kill player driver on cook-off (fairly likely).
=> Vehicle Coasting - Fixes

addons/miscFixes/CfgCloudlets.hpp, addons/miscFixes/patchGM/CfgAmmo.hpp
This PR reverts GM artillery trail to their vanilla settings by recreating the `CfgCloudlets` class, as well as `effectFly` class. Addresses https://github.com/BourbonWarfare/POTATO/issues/644
=> miscFixes - Remove smoke trail from GM artillery

addons/assignGear/functions/fnc_assignGearSupplyBox.sqf, addons/assignGear/functions/fnc_assignGearVehicle.sqf
Sometimes `fnc_assignGearSupplyBox` skips child config classes. It would seem `configProperties` doesn't always work in `missionConfigFile`.
=> assignGear - Fix Supply Boxes Config Skipping

addons/adminMenu/Interrupt_adminMenu.hpp, addons/adminMenu/functions/fnc_uihook_resetMarkersButton.sqf, addons/adminMenu/script_component.hpp, addons/spectate/functions/fnc_checkToReopen.sqf, addons/spectate/functions/fnc_setup.sqf, addons/spectate/functions/fnc_ui_handleDraw3D.sqf, addons/spectate/functions/fnc_ui_handleKeyDown.sqf, addons/spectate/script_component.hpp, addons/zeusUtils/functions/fnc_drawMarkers.sqf
This PR (should be three, sorry):
- Fixes admin menu markers tab reset markers on a unit button.
- Changes tags toggle to cycle through none/drawing markers/tags
- Fixed zeusUtils markers ASL/ATL mismatch
=> Spectate and Markers - Added spectate marker vision mode and fixed zeus marker display

addons/customGear/ACE_CSW_Groups.hpp, addons/customGear/CfgMagazines.hpp, addons/customGear/config.cpp
This PR adds CSW mags for both potato HE and HEDP grenades for the Mk19
=> Custom Gear - Adds Potato 40x53mm CSW Magazines

addons/arsenalExport/XEH_PREP.hpp, addons/arsenalExport/functions/fnc_arsenalOpened.sqf, addons/arsenalExport/functions/fnc_buttonClick.sqf, addons/arsenalExport/functions/fnc_export.sqf, addons/arsenalExport/functions/fnc_exportBoxes.sqf
This PR:
- Adds an export button for FT, LAT, MAT, HAT, MMG, and HMG resupply boxes based on arsenal load outs.
- Added HMG and HAT to work with CSW weapons, will take magazines if loaded into a unit's inventory
- Fixes Carryall and Alt. Helmet values being ignored on export
- Added button for side custom explosive and smoke grenades (still requires some effort for SL+)
=> arsenalExport - Add Export Options for Resupply Boxes & Misc Fixes

addons/missileGuidanceCompat/patchGM/ACE_CSW_Groups.hpp, addons/missileGuidanceCompat/patchGM/CfgAmmo.hpp, addons/missileGuidanceCompat/patchGM/CfgMagazines.hpp, addons/missileGuidanceCompat/patchGM/CfgVehicles.hpp, addons/missileGuidanceCompat/patchGM/CfgWeapons.hpp, addons/missileGuidanceCompat/patchGM/config.cpp, addons/missileGuidanceCompat/patchGM/script_component.hpp
This PR adds Missile Guidance to the Milan missile used in GM. All vehicles except for Marder variants are changed to a new magazine that uses Missile Guidance, as Missile Guidance can not currently handle turrets on turrets like the Marder's Milan turret. To work around that, this PR:
- Creates alternate magazines and ammo
- Makes changes to the GM CSW Compat if the subaddon is loaded.
- Replaces magazines for the MILAN variants of the,
- Fuchs
- M113A1G
- Iltis
=> missileGuidanceCompat - Add MG Version of Milan for use with Specific Vehicles

addons/customGear/CfgAmmo.hpp, addons/missileGuidanceCompat/patchCWR/config.cpp
This PR:
- Fixes a missing ammo class for the CWR3 Redeye
- Ups the Potato HEDP penetration `hit` value from 70 to 90
=> missileGuidanceCompat - Temporary fix for Missing Redeye Ammo

addons/arsenalExport/XEH_preInit.sqf, addons/arsenalExport/functions/fnc_buttonClick.sqf, addons/arsenalExport/functions/fnc_export.sqf, addons/arsenalExport/functions/fnc_exportBoxes.sqf
This PR will:
- Add error checking for exporting AT crates
- Prefer GP-30 launched grenades for resupply box export
- Disable arsenal export dialog when not in the editor, an editor launched mission, or the ACE Arsenal launched from main menu
=> arsenalExport - Fix Export Errors & Disable Outside of Editor and ACE Arsenal

addons/miscFixes/patchRHSAFRF/CfgAmmo.hpp, addons/miscFixes/patchRHSAFRF/config.cpp
The RHS 9M113 on the BMP-1 and BMD series IFVs uses a turret on turret configuration not supported by Missile Guidance. This PR disables missile guidance for the 9M113 and reverts overridden parameters.
=> miscFixes - Fix RHS 9M113 AMG 

addons/briefing/functions/fnc_sortOrbat.sqf
This PR:
- Fixes missing "APC" and "technical" groups
- Fix leading space when no platoon element
This PR will continue to be updated as needed until the date for the next POTATO update is set
=> Briefing - Fix Sorted ORBAT Formatting

addons/missileGuidanceCompat/patchGM/CfgVehicles.hpp
The GM M113A1G Milan is also a turret on turret, removing the missile guidance to avoid issues.
=> missileGuidanceCompat - Remove Missile Guidance from GM M113A1G

addons/units/subClasses/unitDef.hpp
I think arma doesn't like the `ifdef` inside the macro block?
when loading raw configs (raw pbos or  hemtt --norap)
```
ErrorMessage: File z\potato\addons\units\nolambs\CfgVehicles.hpp, line 2: '/CfgVehicles/potato_nolambs_e_rifleman.ifdef': 'c' encountered instead of '='
Application terminated intentionally
```
not really sure why, but this change seems to do the same thing and loads ok
=> tweak nolamb macro

addons/markers/functions/fnc_drawMarkers.sqf, addons/markers/initSettings.inc.sqf
This PR adds a setting to allow the intra-group markers to be set to player only, skipping all other units except for the current player.
=> markers - Player Only Intra-Group Markers Setting

addons/arsenalExport/XEH_preInit.sqf
This PR disable the export menu from showing up in the BI arsenal since it often does not work and currently covers the right pane of the interface.
=> arsenalExport - Disable BI Loadout Export Menu

addons/miscFixes/patchCUP/config.cpp
This PR removes the two side gunners from being automatically filled (by both Arma and our createCrew function) when the vehicle spawned as they normally would be crewed by dismounts.
=> miscFixes - Remove Autofill Side Turrets for CUP BMP-3

addons/dui_goby/initSettings.inc.sqf
This PR utilizes the alpha channel setting for the DUI goby sub-addon.
=>  DUI GoBy - Use Alpha Channel on CBA Setting

addons/miscFixes/config.cpp, addons/miscFixes/patchCUP/config.cpp, addons/miscFixes/patchCUPTerrains/config.cpp, addons/miscFixes/patchCWRBAF/CfgVehicles.hpp, addons/miscFixes/patchGM/CfgWeapons.hpp
This PR:
- Changes `CfgDamageAround` to lower building collapse damage to non-lethal levels.
- Increases health on select CUP terrains buildings and the vanilla construction sight.
- Fixes a UBC chnge in the GM smoke edit PR #702
=> miscFixes - Lower Building Collapse Damage and Increase Weaker Building Armor

addons/missionTesting/XEH_postInit.sqf
- Line 13: Reworded and abbreviated the "terrain imbalance" checkbox
- Line 33: Added new "vehicle role" checkbox in accordance with new policy that co-pilot roles require pilot qual and should be treated similarly to pilots*
- Line 42: Clarified objective time frame conditions
- Line 47-48: Added AMA checkboxes regarding damage reasonability
- Line 62: fix'd spelling
*this will not affect their position in the queue, this is meant to ensure the co-pilot has core competencies
=> Testing Menu Revitalization

addons/settings/BW_Settings.inc.sqf
- Sets the default visual range of the DUI compass to the current max range (50m)
- Enables the Vehicle Compass again
- Sets the Vehicle Crew compass scale, fixing the previous issue of giant icons in the DUI hud when in a vehicle - this one might need more testing with various UI scales to verify?
- Increases the distance warning from 3m to 5m
The only thing that I really will advocate for is the compass range stuff, everything else was just something I discovered by coincidence when testing and am fine with splitting them up if we don't like the other stuff being on.
=> DUI Compass Settings Update

addons/armor_modifier_ace/XEH_PREP.hpp, addons/armor_modifier_ace/XEH_preInit.sqf, addons/armor_modifier_ace/functions/fnc_getHitpointArmor.sqf, addons/armor_modifier_ace/functions/fnc_getItemArmor.sqf, addons/armor_modifier_ace/functions/fnc_handleDamage.sqf, addons/settings/BW_Settings.inc.sqf, addons/settings/XEH_preInit.sqf
ref https://github.com/acemod/ACE3/issues/9217
copies changes to handleDamage and fully copies old versions of getHitpointArmor funcs
test code (captured from shooting AI in chest)
results in same wounds from before
```
{
_x call potato_armor_modifier_ace_fnc_handleDamage;
} forEach [[[q2,"head",0,q1,"B_65x39_Caseless",2,q1,"hithead",true,3]],[[q2,"",0.464393,q1,"B_65x39_Caseless",-1,q1,"",true,4]],[[q2,"",0.464393,q1,"B_65x39_Caseless",-1,q1,"",true,0]],[[q2,"face_hub",0.0133762,q1,"B_65x39_Caseless",0,q1,"hitface",true,1]],[[q2,"neck",0.0110848,q1,"B_65x39_Caseless",1,q1,"hitneck",true,1]],[[q2,"spine2",0.114368,q1,"B_65x39_Caseless",5,q1,"hitdiaphragm",true,1]],[[q2,"spine3",0.114368,q1,"B_65x39_Caseless",6,q1,"hitchest",true,1]],[[q2,"arms",0.0108112,q1,"B_65x39_Caseless",8,q1,"hitarms …
```
=> Armor Mod - Adjust for ace 3.20 changes

addons/miscFixes/patchCUP/config.cpp
This PR replace the zoom range and optic model of the CUP M47 Dragon launcher with the ACE version.
=> miscFixes - CUP - Replace CUP M47 Optic & Zoom with ACE Equivalent

addons/miscFixes/patchPhoton/CfgVideoOptions.hpp, addons/miscFixes/patchPhoton/config.cpp
This PR does what the name says and returns the Low, Normal, and High particle settings back to vanilla values.
=> miscFixes - PhotonVFX - Settings Revert to Vanilla to Minimie Particle Deletion

addons/miscFixes/patchRHSAFRF/CfgAmmo.hpp
- Increases caliber and adds hit values to RHS T-72/T-90 rounds comparable to CUP values for same/similar rounds
- In testing, this allowed for RHS tanks to actually penetrate and kill CUP/CWR3 M60A3s and in some cases (3BM46 and 69) penetrate CUP/CWR3 M1A1s
- Rounds might be a little overtuned due to the submunitions also having hit values, but imo this at least makes RHS tanks usable against certain CUP assets
=> RHS T-72 Ammo Buffs

addons/miscFixes/patchCUP/config.cpp
Adjusts the previous CUP M249 recoil adjustment to be tuned down following [feedback in the discord.](https://discord.com/channels/204621032428929025/1393171695401173083)
This changes the recoil from a significant permanent up-and-to-the-right recoil to a much softer temporary "bouncy" recoil. The intent is to reduce the need to control the recoil with the mouse, but still prevent the M249 from being a laser beam @ 100m.
=> M249 Recoil Re-Adjustment

addons/assignGear/functions/fnc_assignGearMan.sqf
This PR delays init until after `setUnitLoadout` runs. `setUnitLoadout` is delayed to address changes made in Arma 3 v2.20.
=> assignGear - Ensure init Code is Run After setUnitLoadout

addons/miscFixes/patchCUP/CfgAmmo.hpp, addons/miscFixes/patchCUP/config.cpp
"Nerfs" the CUP GRAD, Hilux MLRS, Hilux UB-32 launcher damage by removing the inherited 230mm submunition from the warhead. This makes the damage much more reasonable instead of being portable nukes.
Additionally, buffs the Hilux MLRS and UB-32 accuracy so that way it's reasonably usable for grid-square targets post-damage nerf.
=> CUP MLRS Submunitions Fix

addons/miscFixes/patchCWRBAF/CfgVehicles.hpp, addons/miscFixes/patchGM/CfgAmmo.hpp
This PR 
- Fixed the FFV seats not working for the Potato FV432
- Allowed turning in on the Potato FV432 (some animation clipping)
=> miscFixes - patchCWRBAF - Fix Potato FV432

addons/aiCfgFixes/CfgAmmo.hpp, addons/aiCfgFixes/aiWeapons/CfgWeapons.hpp, addons/aiCfgFixes/aiWeapons/config.cpp, addons/aiCfgFixes/gm/CfgAmmo.hpp, addons/aiCfgFixes/gm/config.cpp, addons/aiCfgFixes/rhs_hlc/CfgAmmo.hpp
This PR allows certain PG-7 rounds to be use against infantry. In addition, it adds 3 variants of the CUP RPG-7V launcher intended for AI use. These launchers change AI engagement ranges and round dispersion in an attempt to allow AI to have RPG-7s and not hit everything within 500m in one shot.
TODO
=> aiCfgFixes - RPG7 Ammo and Weapons
