BourbonWarfare/POTATO

- addons/adminMenu/Interrupt_adminMenu.hpp
- addons/adminMenu/XEH_postInit.sqf
- addons/adminMenu/XEH_preInit.sqf
- addons/adminMenu/functions/fnc_uihook_resetGearButton.sqf
- addons/adminMenu/functions/fnc_uihook_tabChange.sqf
- addons/adminMenu/script_component.hpp
> Add reset gear button to fix loadout issues

- addons/reinforceToHC/XEH_postInit.sqf
- addons/reinforceToHC/config.cpp
- addons/reinforceToHC/functions/fnc_reinforcementsCreateUnits.sqf
- addons/reinforceToHC/functions/fnc_setupReinforcements.sqf
- addons/reinforceToHC/functions/fnc_spawnReinforcements.sqf
> Reinforcement unit pools

- addons/zeusMonitor/$PBOPREFIX$
- addons/zeusMonitor/CfgEventHandlers.hpp
- addons/zeusMonitor/RscDisplayCurator.hpp
- addons/zeusMonitor/XEH_PREP.hpp
- addons/zeusMonitor/XEH_preInit.sqf
- addons/zeusMonitor/XEH_preStart.sqf
- addons/zeusMonitor/config.cpp
- addons/zeusMonitor/functions/fnc_toggleAcreSepcator.sqf
- addons/zeusMonitor/functions/fnc_zeusInterfaceOpenedEH.sqf
- addons/zeusMonitor/functions/script_component.hpp
- addons/zeusMonitor/script_component.hpp
> Zeus - Show AI Count and ACRE Spectator Toggle

- addons/miscFixes/config.cpp
Lets us drop MELB without breaking missions
> MELB -> RHS compat

- addons/zeusHC/CfgVehicles.hpp
- addons/zeusHC/functions/fnc_createEntityZeus.sqf
- addons/zeusHC/functions/fnc_garrisonModule.sqf
Makes the potato HC modules (that are placeable in the editor) syncable
resolves #39
> Syncable modules

- addons/aiFrameworks/ACE_Settings.hpp
- addons/aiFrameworks/vcom/functions/fnc_armEmptyStatic.sqf
- addons/aiFrameworks/vcom/functions/fnc_defaultSetup.sqf
- addons/aiFrameworks/vcom/functions/fnc_flankManeuver.sqf
- addons/aiFrameworks/vcom/functions/fnc_gunnerTargeting.sqf
- addons/aiFrameworks/vcom/functions/fnc_plantCharge.sqf
- addons/aiFrameworks/vcom/functions/fnc_startBrain.sqf
- addons/aiFrameworks/vcom/functions/fnc_vehicleHandle.sqf
Should fix some of the issues seen during the VCOM tests.
> Vcom tweaks

- addons/teamColors/$PBOPREFIX$
- addons/teamColors/CfgEden.hpp
- addons/teamColors/CfgEventHandlers.hpp
- addons/teamColors/XEH_PREP.hpp
- addons/teamColors/XEH_preInit.sqf
- addons/teamColors/XEH_preStart.sqf
- addons/teamColors/config.cpp
- addons/teamColors/functions/fnc_setColor.sqf
- addons/teamColors/functions/script_component.hpp
- addons/teamColors/script_component.hpp
Tested locally and on a local dedicated server, seems to work okay, can't really test multi-player though.
> Potato color teams

- addons/zeusHC/functions/fnc_createEntityZeus.sqf
- addons/zeusHC/functions/fnc_garrisonModule.sqf
Do we want to do this, or build in some sort of queue that goes through the operations on start? Resolves #66
> update potato AI to run after players become players

- addons/radios/functions/fnc_babelAttributeLoad.sqf
- addons/radios/functions/fnc_babelAttributeSave.sqf
- addons/radios/functions/fnc_babelControlBabelChange.sqf
- addons/radios/functions/fnc_babelControlLoad.sqf
- addons/radios/functions/fnc_babelControlSetChange.sqf
- addons/radios/functions/fnc_channelAttributeLoad.sqf
- addons/radios/functions/fnc_initializeRadios.sqf
- addons/radios/functions/fnc_setBabelList.sqf
Moves babel away from GVARs
Removes log statements that were throwing errors with debug on
Minor code cleanup for the radio component
> Radio fixes

- addons/fixPlayerCount/$PBOPREFIX$
- addons/fixPlayerCount/CfgEventHandlers.hpp
- addons/fixPlayerCount/Displays.hpp
- addons/fixPlayerCount/config.cpp
- addons/fixPlayerCount/functions/fnc_displayLoad.sqf
- addons/fixPlayerCount/functions/fnc_displayUnload.sqf
- addons/fixPlayerCount/functions/fnc_displayUpdate.sqf
- addons/fixPlayerCount/functions/script_component.hpp
- addons/fixPlayerCount/script_component.hpp
- addons/ratios/functions/fnc_displayUpdate.sqf
Should fix both the ratio counter, and the actual display of the player count.
> Fix player count issues (until BI fixes them)

- addons/miscFixes/config.cpp
Fixes the broken Afghanistan uniform 6 (turns it into the no hat version)
> Shim broken uniform

- addons/radios/XEH_PREP.hpp
- addons/radios/XEH_postInit.sqf
- addons/radios/functions/fnc_addAcreBriefing.sqf
- addons/radios/functions/fnc_configureRadios.sqf
- addons/radios/functions/fnc_initializeRadios.sqf
- addons/radios/functions/fnc_reinitializeRadios.sqf
- addons/radios/functions/fnc_setChannel.sqf
- addons/radios/functions/fnc_setupPlayer.sqf
Adds support for `ace_player` so `FUNC(setupPlayer)` will rerun on each change
Respawns, including side change respawns, should work
As well as zeus RCing units.
> Respawn / Zeus support for radios

- addons/miscFixes/CfgEventHandlers.hpp
https://feedback.bistudio.com/T120418#1518242
> Fix chat text not showing up after using splendid cam

- addons/missionModules/XEH_PREP.hpp
- addons/missionModules/functions/fnc_setFog.sqf
- addons/missionModules/functions/fnc_setTime.sqf
- addons/missionModules/functions/fnc_setWeather.sqf
- Move the parameter functions out of the framework
- Document parameter functions
- Simplify (hopefully) the parameter functions
> Add mission parameter based functions

- addons/briefing/CfgEden.hpp
- addons/briefing/XEH_PREP.hpp
- addons/briefing/XEH_postInit.sqf
- addons/briefing/functions/fnc_addBriefingToUnit.sqf
- addons/briefing/functions/fnc_addCredits.sqf
- addons/briefing/functions/fnc_addMedicalNotes.sqf
- addons/briefing/functions/fnc_addOrbat.sqf
- addons/briefing/functions/fnc_addResponsibilitiesDiary.sqf
- addons/briefing/functions/fnc_addTreatmentDiary.sqf
- addons/briefing/functions/fnc_addWoundDiary.sqf
- addons/briefing/functions/fnc_briefingAttributeLoad.sqf
- addons/briefing/functions/fnc_briefingAttributeSave.sqf
- addons/briefing/functions/fnc_convertHTMLToNewLine.sqf
- addons/briefing/functions/fnc_convertNewLineToHTML.sqf
- addons/briefing/functions/fnc_displayDanger.sqf
- addons/briefing/functions/fnc_setBriefingVar.sqf
- addons/briefing/functions/script_component.hpp
- addons/briefing/script_component.hpp
- Add comments to all the functions
- Changes the way the briefing is stored (no linebreaks in the sqm, has issues with that when trying to binarize/compress the files)
- Adds a advanced medical briefing. Resolves #83 
- Updated the methodology of assigning good/bad values to wounds/treatments to hopefully stay ever green.
> Briefing updates

- addons/assignGear/functions/fnc_addItemsToContainer.sqf
- addons/assignGear/script_component.hpp
Allows weapons to be added to a unit's uniforms/vest/backpacks.
Only lingering question: do we have to worry about attachments/preloading the weapon?
> Allow weapons to be added from the loadout config to containers

- addons/teamColors/functions/fnc_setColor.sqf
- addons/teamColors/functions/fnc_teamAttributeLoad.sqf
- addons/teamColors/functions/fnc_teamAttributeSave.sqf
- addons/teamColors/functions/fnc_teamColorChange.sqf
Should fix team colors, only tested locally though, a few person MP test should really be executed before merging.
> Team colors fix

- addons/assignGear/XEH_preInit.sqf
> Add framedelay

- addons/zeusHC/functions/fnc_createEntityDismounts.sqf
- addons/zeusHC/functions/fnc_createEntityLocal.sqf
- addons/zeusHC/functions/fnc_createEntityZeus.sqf
find nearest vehicle if attached object is null
Should resolve #60
> Fix dismounts module

- addons/miscFixes/CfgWeapons.hpp
http://i.imgur.com/cvwvv62.gifv
> Predator Vision

- addons/markers/XEH_PREP.hpp
- addons/markers/functions/fnc_addGestureColor.sqf
- addons/markers/functions/fnc_setMarker.sqf
Simple code addition to set the map gesture to the color of the group's unit color. Should be nice for large scale briefings
> Add gesture color based on map marker

- addons/assignGear/functions/fnc_canSetOptic.sqf
- addons/assignGear/functions/fnc_getWeaponArray.sqf
- addons/assignGear/functions/fnc_setOptic.sqf
Removes unneeded toLowers in the optix setup, reworks how attachments are checked in the weaponsArray so case sensitivity is not an issue.
> Fix case sensitivity issues with attachements

- addons/adminMenu/Interrupt_adminMenu.hpp
- addons/adminMenu/XEH_PREP.hpp
- addons/adminMenu/XEH_postInit.sqf
- addons/adminMenu/functions/fnc_uihook_resetGearButton.sqf
- addons/adminMenu/functions/fnc_uihook_resetSpectateButton.sqf
- addons/adminMenu/functions/fnc_uihook_tabChange.sqf
- addons/adminMenu/script_component.hpp
- addons/briefing/XEH_PREP.hpp
- addons/briefing/XEH_postInit.sqf
- addons/briefing/functions/fnc_addIntentToZeus.sqf
- addons/spectate/functions/fnc_exit.sqf
- addons/spectate/functions/fnc_init.sqf
- addons/spectate/functions/fnc_ui_handleMapDraw.sqf
> Spectate Fixes

- addons/arsenalExport/$PBOPREFIX$
- addons/arsenalExport/CfgEventHandlers.hpp
- addons/arsenalExport/XEH_PREP.hpp
- addons/arsenalExport/XEH_postInit.sqf
- addons/arsenalExport/XEH_preInit.sqf
- addons/arsenalExport/XEH_preStart.sqf
- addons/arsenalExport/config.cpp
- addons/arsenalExport/functions/fnc_arsenalOpened.sqf
- addons/arsenalExport/functions/fnc_buttonClick.sqf
- addons/arsenalExport/functions/fnc_export.sqf
- addons/arsenalExport/functions/script_component.hpp
- addons/arsenalExport/script_component.hpp
> Arsenal Export

- addons/adminMenu/Interrupt_adminMenu.hpp
- addons/adminMenu/XEH_PREP.hpp
- addons/adminMenu/XEH_postInit.sqf
- addons/adminMenu/functions/fnc_uihook_resetMarkersButton.sqf
- addons/adminMenu/functions/fnc_uihook_resetSpectateButton.sqf
- addons/markers/XEH_postInit.sqf
- addons/markers/functions/fnc_getSideArray.sqf
- addons/markers/functions/fnc_initMarkerHash.sqf
Should fix the marker init issues we've been seeing off and on. Even if it doesn't it adds a way to re-init a player's marker. (Not exposed to the player as it will remove 'dead' player/group markers)
> Marker fixes

- addons/missionModules/XEH_postInit.sqf
- addons/missionModules/functions/fnc_skillDebug.sqf
- addons/radios/functions/fnc_addAcreBriefing.sqf
- addons/radios/functions/fnc_channelControlLoad.sqf
- addons/spectate/functions/fnc_ui_handleDraw3D.sqf
- addons/vz99/functions/fnc_levelToGround.sqf
- addons/zeusFactory/functions/fnc_createTransport.sqf
- addons/zeusFactory/functions/fnc_dispatch.sqf
- addons/zeusFactory/functions/fnc_factoryLoop.sqf
- tools/sqf_linter.py
- Fix some BANZI stuff
- acco - could you double check `addons/radios/functions/fnc_channelControlLoad.sqf`
- everything else is minor stuff (e.g. var exists from a higher scope)
> Lint cleanup

- addons/adminMenu/functions/fnc_uihook_supplySpawn.sqf
- addons/core/XEH_PREP.hpp
- addons/core/XEH_postInit.sqf
- addons/core/functions/fnc_addToCurator.sqf
- addons/core/functions/fnc_addToCuratorServer.sqf
- addons/zeusFactory/functions/fnc_ai_paradrop.sqf
- addons/zeusFactory/functions/fnc_createGroup.sqf
- addons/zeusFactory/functions/fnc_createTransport.sqf
- addons/zeusFactory/functions/fnc_factoryLoop.sqf
- addons/zeusHC/functions/fnc_createCrew.sqf
- addons/zeusHC/functions/fnc_createEntityDismounts.sqf
- addons/zeusHC/functions/fnc_createEntityLocal.sqf
- addons/zeusHC/functions/fnc_createGroup.sqf
- addons/zeusHC/functions/fnc_spawnAVicSpawnLocal.sqf
> Add script created objects to curator

- addons/missionTest/$PBOPREFIX$
- addons/missionTest/Cfg3DEN.hpp
- addons/missionTest/config.cpp
- addons/missionTest/functions/fnc_onMissionSave.sqf
- addons/missionTest/functions/script_component.hpp
- addons/missionTest/script_component.hpp
> Self test missions on save

- addons/core/script_macros.hpp
- addons/zeusRecon/$PBOPREFIX$
- addons/zeusRecon/CfgEventHandlers.hpp
- addons/zeusRecon/CfgVehicles.hpp
- addons/zeusRecon/XEH_PREP.hpp
- addons/zeusRecon/XEH_preInit.sqf
- addons/zeusRecon/XEH_preStart.sqf
- addons/zeusRecon/config.cpp
- addons/zeusRecon/functions/fnc_drawIcons2d.sqf
- addons/zeusRecon/functions/fnc_drawIcons3d.sqf
- addons/zeusRecon/functions/fnc_getIcon.sqf
- addons/zeusRecon/functions/fnc_groupReport.sqf
- addons/zeusRecon/functions/fnc_moduleInit.sqf
- addons/zeusRecon/functions/fnc_reconStateMachine.sqf
- addons/zeusRecon/functions/fnc_zeusInterfaceOpenedEH.sqf
- addons/zeusRecon/functions/script_component.hpp
- addons/zeusRecon/script_component.hpp
Attempts to have zeus AI give contact reports much like you might get from real players.
Only reports what zeus AI have actually seen (instead of zues magically seeing all players)
Enemies reported with orange marks, showing composition and time last seen:
> Zeus Recon

- addons/miscFixes/CfgWeapons.hpp
Deprecates dumb nlaw ( closes #165 )
> Deprecate dumb nlaw

- addons/adminMenu/Interrupt_adminMenu.hpp
- addons/adminMenu/XEH_PREP.hpp
- addons/adminMenu/functions/fnc_uihook_resetMedicalButton.sqf
> Add Medical reset to admin menu fixes

- addons/assignGear/XEH_preInit.sqf
- addons/assignGear/functions/fnc_assignGearMan.sqf
- addons/assignGear/functions/fnc_requestPlayerGear.sqf
Resolves #189 
- Runs init for 3den
- Removes watch dog
> 3den gear fix

- addons/markers/XEH_postInit.sqf
> Fix variables

- addons/assignGear/functions/fnc_getWeaponArray.sqf
Resolves #211 
I'm amazed we haven't run into this before.....
> Add case insensitive magazine check

- addons/briefing/functions/fnc_addCredits.sqf
I think this is information you would generally have a basic idea of
> Add sunrise/sunset times to credits

- addons/core/CfgFactionClasses.hpp
- addons/miscFixes/XEH_serverPostInit.sqf
- addons/missionModules/CfgVehicles.hpp
- addons/missionModules/XEH_PREP.hpp
- addons/missionModules/config.cpp
- addons/missionModules/functions/fnc_moveHcsToModule.sqf
- addons/missionModules/functions/fnc_moveHcsToPos.sqf
- addons/zeusHC/CfgFactionClasses.hpp
- addons/zeusHC/CfgVehicles.hpp
> Normalize hc pos

- addons/adminMenu/functions/fnc_uihook_weaponTest.sqf
- addons/arsenalExport/functions/fnc_buttonClick.sqf
- addons/arsenalExport/functions/fnc_export.sqf
- addons/assignGear/functions/fnc_getWeaponArray.sqf
- addons/cswCompat/config.cpp
- addons/massCompat/script.sqf
- addons/missionTest/Cfg3DEN.hpp
- addons/missionTest/functions/fnc_fixFloating.sqf
- addons/missionTest/functions/fnc_onMissionSave.sqf
Use CBA_fnc_compatibleMagazines
Fix export not working from 3den on non-player unit
Fix export not using loaded mag
Fix warning about compat missing units[]
Add toolbar action to level units to ground (fix floating)
> Add support for mag wells and more

- addons/missionTest/functions/fnc_onMissionSave.sqf
`Nato Rifleman A1` would become `*Mark*Nato Rifleman A1` if slot uses dlc items
> Auto-tag slots using premium dlc

- .gitignore
- addons/recruits/CfgEventHandlers.hpp
- addons/recruits/XEH_serverWebhook.sqf
- extensions/.gitignore
- extensions/CMakeLists.txt
- extensions/Webhook.cpp
> Recruit Tracker to Discord Webhook - (dedicated server only) 

- addons/aiVehicleBail/CfgVehicles.hpp
> Add fire ring config option to CUP vehicles

- addons/hitEffects/CfgCloudlets.hpp
If this is still too much we can tweak more
> (Hit Effects) Lower smoke linger, get rid of removed variable

- addons/cswCompat/CfgMagazines.hpp
- addons/cswCompat/CfgVehicles.hpp
- addons/cswCompat/CfgWeapons.hpp
CUP v16 has native csw compats based on ours
> Switch cswCompat to CUP's native version

- addons/miscFixes/RscDisplayMain.hpp
- addons/miscFixes/config.cpp
you have to have connected at least once before for this to show up
> Add main menu button to quickly connect to server

- addons/plotArmor/$PBOPREFIX$
- addons/plotArmor/config.cpp
- addons/plotArmor/script_component.hpp
Adding directly to potato
Fixed  `No entry bin\config dot bin/CfgWeapons/ItemInfo` popup
>  SagJangi Plot Armor

- addons/missionTesting/functions/fnc_briefingsChangeSide.sqf
- addons/missionTesting/functions/fnc_generateReport.sqf
Adds BWMF version information to the MM Report, and fixes small issue with East Administration Brief not displaying in GUI.
> Mission testing hotfix

- addons/settings/BW_Settings.sqf
- addons/zeusFactory/CfgZeusFactory.hpp
Updated existing vehicles to more neutral color schemes and added new vehicles to arrays.
> Update Potato Factory with new vehicles

- .gitignore
- addons/zeusFactory/CfgVehicles.hpp
- hemtt.toml
- tools/build.py
new mikro tools won't pack dev builds
drop hemtt.exe into potato root and build.py will use it
> use hemtt for dev builds

- addons/adminMenu/Interrupt_adminMenu.hpp
- addons/adminMenu/functions/fnc_uihook_resetGearButton.sqf
- addons/adminMenu/functions/fnc_uihook_tabChange.sqf
- addons/adminMenu/script_component.hpp
Can pick different loadouts when hitting the "Reset Gear" button
> adminMenu - Allow resetting gear to different loadout

- addons/spectate/Displays.hpp
- addons/spectate/XEH_PREP.hpp
- addons/spectate/functions/fnc_acreSpectateCompat.sqf
- addons/spectate/functions/fnc_checkToReopen.sqf
- addons/spectate/functions/fnc_setup.sqf
- addons/spectate/script_component.hpp
> acreSpectateCompat

- addons/assignGear/XEH_preInit.sqf
- addons/assignGear/functions/fnc_assignGearVehicle.sqf
Mostly for pilots, but also just a nice QOL change for vehicle crews.
> Adds toolkits to all vehicles

- addons/aiCfgFixes/CfgAmmo.hpp
- addons/aiCfgFixes/CfgWeapons.hpp
- addons/aiCfgFixes/functions/fnc_ensurePlayerBurst.sqf
- addons/aiCfgFixes/script_component.hpp
this is still needed because BI don't want to fix it
https://feedback.bistudio.com/T121635
fixes any and all issue with mismatched configs
> update AI cfg tweaks configs

- addons/radios/script_component.hpp
Provides support for the addition of a dedicated medical net in framework version 5.3.1
> Medical Net

- addons/miscMedical/XEH_postInit.sqf
Calculates pressure at a given distance from the explosive and checks if it could be fatal. Real data used, so this _is_ realistic; see papers referenced in code
> Add overpressure deaths from explosives

- addons/settings/BW_Settings.sqf
> Settings - Update for new ace cprSuccessChance settings

- addons/settings/BW_Settings.sqf
ref `https://github.com/acemod/ACE3/pull/8162`
> Settings - Allows diagnosing death/CA

- addons/miscFixes/CfgVehicles.hpp
- addons/miscFixes/config.cpp
Fixes hard popup `No entry 'bin\config.bin/CfgCloudlets.housedestructionsmoke'.`
> MiscFixes - Fix Descrution effects popup from fajita

- addons/massCompat/magwells_338LM.hpp
- addons/massCompat/magwells_65x39.hpp
- addons/massCompat/magwells_762x51.hpp
- addons/massCompat/magwells_762x54.hpp
> Fix old mags

- addons/miscFixes/CfgVehicles.hpp
- addons/miscFixes/config.cpp
- addons/settings/BW_Settings.sqf
ace_fortify added some progress bar stuff, changed to zero so it doesn't effect old missions
our mission makers can still change if they want to use it
> Fort new settings

- addons/spectate/functions/fnc_prepareSpectator.sqf
Untested code, just hope that it works
> Fix names disappearing when a unit dies immediately

- addons/arsenalExport/functions/fnc_arsenalOpened.sqf
- addons/arsenalExport/functions/fnc_buttonClick.sqf
- addons/arsenalExport/functions/fnc_export.sqf
Should be ready to go. 
Fairly straight forward, and testing shows that it works. Will need someone with a keen eye to go over it.
> Arsenal export improvements

- addons/missileGuidanceCompat/$PBOPREFIX$
- addons/missileGuidanceCompat/CfgAmmo.hpp
- addons/missileGuidanceCompat/CfgMagazines.hpp
- addons/missileGuidanceCompat/config.cpp
- addons/missileGuidanceCompat/script_component.hpp
merge when ACE missile guidance latest push is merged
> first pass at adding guidance to all CUP missiles

- addons/miscFixes/CfgWeapons.hpp
- addons/miscFixes/config.cpp
Close #360 
Seems to sound the same as cup without jsrs
testing code
```
player addAction ["AI Shoot", {
[] spawn {
while {true} do {
sleep 0.1;
x3 = weaponState [v, [-1]];
vd forceWeaponFire [x3 #1, x3 #2];
};
};
}];
```
> miscFixes - Fix JSRS minguns

- addons/adminGun/$PBOPREFIX$
- addons/adminGun/CfgAmmo.hpp
- addons/adminGun/CfgEventHandlers.hpp
- addons/adminGun/CfgMagazines.hpp
- addons/adminGun/CfgWeapons.hpp
- addons/adminGun/XEH_PREP.hpp
- addons/adminGun/XEH_postInit.sqf
- addons/adminGun/XEH_preInit.sqf
- addons/adminGun/XEH_preStart.sqf
- addons/adminGun/config.cpp
- addons/adminGun/functions/fnc_onFired.sqf
- addons/adminGun/functions/fnc_physicsPFH.sqf
- addons/adminGun/functions/script_component.hpp
- addons/adminGun/script_component.hpp
- addons/adminMenu/Interrupt_adminMenu.hpp
- addons/adminMenu/XEH_PREP.hpp
- addons/adminMenu/functions/fnc_uihook_giveAdminGun.sqf
- addons/adminMenu/script_component.hpp
Just a fun item that is accessed through admin menu. Currently only a physics gun, but theoretically we can add more functionality if wanted. Not tested on MP, but it only uses `setPosASL` and `setVelocity` the latter of which is networked. Otherwise its just local calculations in a PFH and a `lineIntersectsSurface`
> Add "Admin Gun" - Goofy Tool

- addons/zeusFactory/CfgZeusFactory.hpp
- addons/zeusFactory/XEH_PREP.hpp
- addons/zeusFactory/functions/fnc_createGroup.sqf
- addons/zeusFactory/functions/fnc_createTransport.sqf
- addons/zeusFactory/functions/fnc_getSeatInfo.sqf
- addons/zeusFactory/functions/fnc_getTransportType.sqf
- addons/zeusFactory/functions/fnc_zeusAttributes_factory.sqf
Fix #310
it counted cargo seats wrong and would get into an endless loop
> Factory - Fix vehicle cargo seat logic

- addons/settings/BW_Settings.sqf
based off of BW suggestions thread: https://discord.com/channels/204621032428929025/1032153578619543552/1032153578619543552
probably leave this unmerged for ~1month and we can just apply in the addon options on the server, test for a month and then merge if feedback is good
> change ACE Medical TQ application time

- addons/miscMedical/XEH_postInit.sqf
- addons/settings/BW_Settings.sqf
~~this PR will probably grow exponentially with various other changes to `BW_Settings.sqf` that will balance out this change, leave as draft until it's done~~
Edit: ready for merge as-is, other changes can come in future PRs after feedback
> Instakill fix

- addons/missileGuidanceCompat/CfgEventHandlers.hpp
- addons/missileGuidanceCompat/XEH_preInit.sqf
- addons/missileGuidanceCompat/config.cpp
> mg - fix saclos on cup

- addons/missionModules/CfgVehicles.hpp
- addons/missionModules/functions/fnc_identity_module.sqf
> Fix voice module

- addons/miscFixes/patchCUP/config.cpp
This makes the aforementioned weapons suck so much less.
> M240, PKM, M249 Recoil Changes

- addons/arsenalExport/functions/fnc_buttonClick.sqf
> remove "Init" in systemchat when opening arsenal

- addons/miscFixes/patchCUP/config.cpp
Modifies SAW recoil to be correct. Approved by Kilo/Gunner based on pre-public event feedback. Closes #407
> Fixes for #398

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
GitHub-only changes, no ingame effect
> Added OSS requirements

- addons/missionTesting/functions/fnc_briefingsChangeSide.sqf
> Situtation

- addons/respawn/functions/fnc_respawnClient.sqf
- addons/respawn/functions/fnc_triggerRespawn.sqf
- addons/respawn/functions/fnc_ui_handleAdminLoad.sqf
- addons/respawn/script_component.hpp
> respawn - add option to respawn without markers

- .gitignore
- .hemtt/project.toml
- addons/safeStart/functions/fnc_missionTimeWarning.sqf
- addons/zeusFactory/functions/fnc_zeusAttributes_place.sqf
- addons/zeusHC/functions/fnc_createEntityDismounts.sqf
_missionLengthSec was undefined so I don't know if the mission timer has ever worked?
> fix undef/shadow vars

- addons/miscFixes/patchMAA/config.cpp
> Add warning to `MAA_MAAWS_ADM401`

- addons/paradrop/$PBOPREFIX$
- addons/paradrop/CfgEventHandlers.hpp
- addons/paradrop/CfgFactionClasses.hpp
- addons/paradrop/CfgVehicles.hpp
- addons/paradrop/README.md
- addons/paradrop/XEH_PREP.hpp
- addons/paradrop/XEH_postInit.sqf
- addons/paradrop/XEH_preInit.sqf
- addons/paradrop/XEH_preStart.sqf
- addons/paradrop/config.cpp
- addons/paradrop/functions/fnc_dropCargo.sqf
- addons/paradrop/functions/fnc_launch.sqf
- addons/paradrop/functions/fnc_placeIngress.sqf
- addons/paradrop/functions/fnc_registerDz.sqf
- addons/paradrop/functions/fnc_registerEgress.sqf
- addons/paradrop/functions/fnc_registerIngress.sqf
- addons/paradrop/functions/script_component.hpp
- addons/paradrop/script_component.hpp
Readme included: describes how to use feature.
I made this script forever ago, and Cheshire told me they poached it and were giving it to other mission makers. I figured I would tidy it up and allow it to be used in 3den by everyone out of the box.
Module based. Synchronizing objects to modules and modules to modules gives all the functionality wanted. Time to make a paradrop mission: 60 seconds.
Not tested in MP, just went off of gut to see if it works. First mission makers will probably say if its broken in mp
> Add paradrop script, and modules to facilitate quick paradrops

- addons/missionMaking/Cfg3DEN.hpp
- addons/missionMaking/functions/fnc_changeUnitType.sqf
i.e. easy change rifleman to additional aar
not sure if useful?
> 3den - Rightclick menu to change rifleman to other types

- addons/extension/XEH_serverPostInit.sqf
Despite what this might suggest  "// need the endl (\n not working)" the \n should be recognized by discord at the time that the message is posted.
> Recruit List formatting. 

- addons/extension/XEH_serverPostInit.sqf
Should send a message to potato_bot to let players know that the TVT has ended.
> TVT ending bot message

- addons/adminMenu/functions/fnc_endMission.sqf
- addons/adminMenu/functions/fnc_uihook_endMission.sqf
> OCAP implementation and compatibility with POTATO End Mission fnc

- addons/adminMenu/functions/fnc_endMission.sqf
- addons/extension/XEH_serverPostInit.sqf
> Hotfix CBA Macro Formatting. 

- addons/extension/XEH_serverPostInit.sqf
- addons/extension/functions/fnc_botMessage.sqf
Add init for socket connection to PSM and changes location of Player count messages.
> fix tech message and init socket

- addons/miscFixes/patchCUP/config.cpp
> patchCUP - Cleanup WP configs to use ACE's

- addons/miscFixes/patchPTV/config.cpp
> patchPTV - fix weapons

- addons/missileGuidanceCompat/patchMELB/config.cpp
Untested, should work out of box. HEMTT builds though
> Add Missile Guidance to MELB Hellfire

- addons/assignGear/XEH_PREP.hpp
- addons/assignGear/functions/fnc_assignGearPotatoBox.sqf
- addons/assignGear/functions/fnc_assignGearSupplyBox.sqf
- addons/assignGear/functions/fnc_assignGearVehicle.sqf
- addons/assignGear/functions/fnc_getDisposableInfo.sqf
- addons/assignGear/functions/fnc_getWeaponArray.sqf
ref https://github.com/CBATeam/CBA_A3/pull/1663
> AssignGear - Prepare for changes to cba_disposable

- addons/miscFixes/patchW28/config.cpp
Normalizes all W28 vest armor with vanilla/CUP values.
> W28 Armor Normalization/Rebalance

- addons/arsenalExport/functions/fnc_arsenalOpened.sqf
> Arsenal Export - Hide when ace_arsenal is hidden

- addons/arsenalExport/functions/fnc_export.sqf
> Arsenal Export - Fix for change to ace extension

- addons/arsenalExport/functions/fnc_arsenalOpened.sqf
> Arsenal Export - Fix showing in vanilla arsenal

- addons/core/XEH_postInit.sqf
> Core - Don't filter spectator chat

- addons/core/script_version.hpp
- addons/miscFixes/patchGM/CfgVehicles.hpp
- addons/miscFixes/patchGM/config.cpp
This PR would add editor and zeus placeable bridges from the GM cDLC. Same content as [this mod](https://steamcommunity.com/sharedfiles/filedetails/?id=3310038876), but without the editor previews.
> GM Placeable Bridges

- addons/spectate/functions/fnc_updateInfo.sqf
Fix #534
shows kills of `effectiveCommander` when target is a vic
> Spectate - Improve vehicle handling

- .hemtt/presets/bw.html
- addons/settings/BW_Settings.inc.sqf
- addons/settings/XEH_preInit.sqf
- Settings changes for upcoming mod changes
- Store some settings that were set only on server
> Settings - Update bw_settings for mod changes

- addons/spectate/functions/fnc_ui_handleListClick.sqf
> spectate - flx handleListClick

- addons/adminMenu/Interrupt_adminMenu.hpp
- addons/serverMonitor/RscDisplayCurator.hpp
This PR does what the name says
> Fixed Admin Menu

- .hemtt/project.toml
- addons/assignGear/functions/fnc_addSupplyBoxActions.sqf
- addons/markers/vehicleTags/init.sqf
- addons/missionTesting/functions/fnc_updateNotesFlag.sqf
- addons/radios/functions/fnc_acreSideControlSideChange.sqf
- addons/setVehicleAmmo/XEH_preInit.sqf
- addons/spectate/functions/fnc_ui_handleDraw3D.sqf
cleanup some undefined/unused vars
> General - Small cleanups

- addons/miscMedical/XEH_postInit.sqf
As name says, every explosion generates at least 3 lines in rpt right now and I don't thing @TheCandianVendingMachine is currently reviewing it for anything.
> Remove DEBUG_MODE_FULL define from miscMedical postInit.sqf

- addons/zeusHC/CfgVehicles.hpp
> Zeus Spawn - Adds MMG team Zeus Spawns

- addons/miscFixes/patchHAFMHelis/config.cpp
Per https://github.com/BourbonWarfare/POTATO/issues/581
Replaced the default NH90 sounds with the JSRS vanilla AW-101 Merlin sounds.
> Adds JSRS Compat for NH90

- addons/miscFixes/patchCUP/config.cpp
This PR does what the name says by fixing this M1038 issue:
https://github.com/user-attachments/assets/9d89fa3a-ff68-43d0-91b6-8011092a2dd7
> miscFixes - patchCUP - Fix M1038 Rear Left Seat

- addons/adminComs/Interrupt_adminComs.hpp
fixed some spelling and made some changes to the admin log list to make it wider (I think? I need to find a better way to edit GUIs)
this is a draft because 
- I'd like to test it 
- I'd like to make it wide enough to see most of the message without hovering
- I'd like to make the admin log stay on screen when the TP/healing menu is open, so you can reference which squad people are requesting TP to, etc
> adjusted some admin menu stuff

- addons/missileGuidanceCompat/CfgMissileTypesNato.hpp
- addons/missileGuidanceCompat/patchVanilla/config.cpp
does what it says. makes laser guided artillery actually be laser guided when not using arty computer
> add laser guided artillery

- addons/zeusHC/functions/fnc_createCrew.sqf
This PR replaces part of the `potato_zeusHC_fnc_createCrew` function to include all crew created when a vehicle is placed through the editor. i.e.,
- Vodniks now spawn with both gunners
- CUP BMP-3s spawn with both side gunners
Other notes:
- In limited testing, the new method for creating the `_crew` array appears to be performant than the current method, we could cache if needed.
- Unsure if this causes issues with effective commander, but didn't find any during limited testing.
> zeusHC - Fill Full Crew

- addons/settings/BW_Settings.inc.sqf
> Settings - Allows medics to use their own items first

- addons/setVehicleAmmo/CfgEden.hpp
ref https://ace3.acemod.org/wiki/framework/rearm-framework#21-allow-rearming-of-scripted-loadouts
> setVehicleAmmo - add setting for ace_rearm to reload the custom loadout

- addons/miscFixes/patchCUP/CfgVehiclesA10A.hpp
- addons/miscFixes/patchCUP/config.cpp
This PR should make the A-10A HMD use CCIP calculation for Bombs,Guns, and Rockets
> Misc Fixes - CUP A-10A CCIP Fix

- addons/armor_modifier_ace/functions/fnc_handleDamage.sqf
This PR moves to keep the `handleDamage` function up to speed with ACE's `ace_medical_engine_fnc_handleDamage`
> AMA - Update Handle Damage to Match ACE

- addons/miscMedical/XEH_postInit.sqf
Cleanup variable names and typing to make sure over pressure runs as expected
> miscMedical - Cleanup Over Pressure Positions

- addons/adminMenu/Interrupt_adminMenu.hpp
- addons/adminMenu/XEH_PREP.hpp
- addons/adminMenu/functions/fnc_reloadMarkersTab.sqf
- addons/adminMenu/functions/fnc_uihook_attachMarkerGroup.sqf
- addons/adminMenu/functions/fnc_uihook_attachMarkerUnit.sqf
- addons/adminMenu/functions/fnc_uihook_deleteMarker.sqf
- addons/adminMenu/functions/fnc_uihook_detachMarker.sqf
- addons/adminMenu/functions/fnc_uihook_tabChange.sqf
- addons/markers/XEH_postInit.sqf
- addons/markers/functions/fnc_addMarkerInfoToHash.sqf
- addons/markers/functions/fnc_becomeGroupLeader_statement.sqf
- addons/markers/functions/fnc_joinGroup_statement.sqf
- addons/markers/functions/fnc_leaveGroup_statement.sqf
- addons/markers/script_component.hpp
- addons/respawn/CfgRespawnGroups.hpp
This PR fixes various bugs with the recent markers update
- Attempt to fix JIP issues
- Mix missing SL post-fix
- Fix a rare reinforce issue when group spawned without FTL.
> Markers - Fixes

- addons/miscMedical/XEH_postInit.sqf
title. should better estimate explosives, and probably be more accurate
> miscMedical - Estimate explosive filler via `ace_frag_gurney_c`

- addons/miscFixes/patchCWRBAF/config.cpp
- addons/missileGuidanceCompat/patchCWRBAF/config.cpp
This PR
- Adds a FV107 with realistic turret and weapon
- Adds MG for CWR3 BAF Javelin SAM
> miscFixes - Adds Compat for CWR3 BAF 

- addons/arsenalExport/functions/fnc_arsenalOpened.sqf
Moved offset so it no longer clips.
> arsenalExport - Fix Menu Offset

- addons/extension/XEH_PREP.hpp
- addons/extension/XEH_serverPostInit.sqf
- addons/extension/functions/fnc_getOrbat.sqf
ref https://github.com/BourbonWarfare/potato_bot/pull/35
> potbot - mission end / orbat

- addons/miscFixes/patchGM/CfgCloudlets.hpp
- addons/miscFixes/patchGM/CfgWeapons.hpp
- addons/miscFixes/patchGM/config.cpp
This PR creates a smoke effect that is smaller than the vanilla version.
> Misc Fixes - Patch GM - Lower GM KPVT Gun Smoke

- addons/adminMenu/functions/fnc_uihook_handleMarkerDialogUI.sqf
- addons/briefing/functions/fnc_sortOrbat.sqf
- addons/markers/functions/fnc_addMarkerInfoToHash.sqf
This PR will:
- Allow the markers system to more gracefully handle unexpected icon strings
- Fix a few more orbat sorting issues
> Briefing and Markers - Fix Orbat Sorting and Catch Bad Map Icon String

- addons/dui_goby/$PBOPREFIX$
- addons/dui_goby/CfgEventHandlers.hpp
- addons/dui_goby/XEH_PREP.hpp
- addons/dui_goby/XEH_postInit.sqf
- addons/dui_goby/XEH_preInit.sqf
- addons/dui_goby/XEH_preStart.sqf
- addons/dui_goby/config.cpp
- addons/dui_goby/functions/fnc_loop.sqf
- addons/dui_goby/functions/fnc_syncPlayer.sqf
- addons/dui_goby/initSettings.inc.sqf
- addons/dui_goby/script_component.hpp
kinda hack dui nametags to add our own stuff
> Mod DUI Nametags to let users show how they want to be called

- addons/safeStart/functions/fnc_initForceEndSafeStart.sqf
This PR will send a message to admins when the mission does not auto end.
> Safe Start - Message Admins When TvT Does Not Autoend

- addons/miscFixes/patchGM/CfgAmmo.hpp
This PR adds the frag compats for the new M56 grenade and 120mm mortar shells
> miscFixes - GM Update ACE Frag Compat

- addons/howTo/XEH_postInit.sqf
- addons/howTo/guides/ace_superDragon.inc.sqf
This PR adds a How-To for the Super Dragon. Based on Chesh's how-to from the mission "Patrol to Nowhere."
> hoWTo - Add Super Dragon How-To

- addons/armor_modifier_ace/compat_gm_ama/CfgWeapons.hpp
- addons/armor_modifier_ace/compat_gm_ama/config.cpp
This PR attempts to resolve AMA not properly functioning on GM helmets.
> AMA - GM Compat - Attempt to Fix Helmet Armor

- addons/miscFixes/patchMEHLAND/config.cpp
This PR restores the full main menu when Mehland is loaded.
> miscFixes - Patch Mehland - Fix Full Main Menu

- addons/adminMenu/Interrupt_adminMenu.hpp
- addons/adminMenu/functions/fnc_uihook_resetMarkersButton.sqf
This PR fixes the fix unit marker button (had been defaulting to everyone since it wasn't working recently).
> adminMenu - Add Feedback and Fix Unit Marker Fix

- addons/missionModules/CfgVehicles.hpp
- addons/missionModules/XEH_PREP.hpp
- addons/missionModules/config.cpp
- addons/missionModules/functions/fnc_zeus_resupplyBoxes.sqf
This PR adds a Zeus module that places all box types defined in CfgLoadouts.
> missionModules - Place All Defined Resupply Boxes

- addons/missionMaking/functions/fnc_onMissionLoad.sqf
> Cleanup UUID temp func

- addons/assignGear/CfgMagazines.hpp
- addons/assignGear/config.cpp
- addons/assignGear/functions/fnc_fillObjectFromConfig.sqf
This PR adds an item in the inventory for resupply boxes to point players to look in ACE Cargo.
> Added info in inventory to check ACE cargo

- addons/armor_modifier_ace/compat_gm_ama/CfgWeapons.hpp
- addons/armor_modifier_ace/compat_gm_ama/dev/vestTest.sqf
- addons/armor_modifier_ace/compat_gm_ama/dev/vestTestRecurse.sqf
- addons/armor_modifier_ace/functions/fnc_handleDamage.sqf
This PR fixes a few entries that have weird inheritance behind the scenes causing missed chest hitpoint damage in previous fix and aligns are handle damage to be more similar to the ACE version.
> Armor Modifier ACE - Compat GM - Fix missing Entries

- addons/adminMenu/Interrupt_adminMenu.hpp
- addons/adminMenu/functions/fnc_uihook_resetMedicalButton.sqf
This PR adds an admin menu button heals the entire group.
TODO:
> adminMenu - Add Heal Full Group Button

- addons/assignGear/functions/fnc_assignGearVehicle.sqf
- addons/miscFixes/patchGM/CfgGlasses.hpp
- addons/miscFixes/patchGM/config.cpp
This PR adds the GM goggles and scrim to the customization options for user profiles.
> Add GM Glasses to Profile Options
